appleboy/gofight

- README.md
> [ci skip] update readme.

- README.md
- example/basic.go
- example/basic_test.go
- example/echo.go
- example/gin.go
> fix #7 add basic handler example.

- README.md
- example/mux.go
- example/mux_test.go
> add mux example. Fix #9

- mocha.go
- mocha_test.go
> Support add form data. Fix #11

- README.md
- example/httprouter.go
- example/httprouter_test.go
> Fix #14 add httprouter example.

- example/httprouter.go
- gofight.go
- gofight_test.go
> Add TestRequest

- framework/echo.go
- framework/gin.go
- gofight.go
- gofight_test.go
> fix #17 support PATCH, HEAD and OPTIONS testing.

- README.md
- gofight.go
> fix #18 update doc and example.

- gofight.go
- gofight_test.go
> Fix #21 add user agent.

- .gitignore
- Makefile
- glide.lock
- glide.yaml
> Fixed #27 support glide package management.

- README.md
- gofight.go
- gofight_test.go
> fixed #33 Change fuc name to camel case format.

- README.md
- gofight.go
- gofight_test.go
> Support cookie

- .travis.yml
- Makefile
- glide.lock
- glide.yaml
> add glide package management.

- .gitignore
- README.md
Started to use gofight so I figured I might as well fix little nitpicks :P
> Fixed typos and added MacOS system files to .gitignore

- README.md
> fix readme POST SetForm

- README.md
- gofight_test.go
> add testing reponse header.

- gofight.go
it allows you to pass any as body
> feat: added setJSONInterface

- framework/gin.go
- gofight_test.go
- vendor/vendor.json
> test: add SetJSONInterface testing

- README.md
- example/beego.go
- example/beego_test.go
Hi, I've added a beego example
> Add + Beego Framework example

- .drone.yml
> chore: upgrade to go1.13

- example/tango.go
- example/tango_test.go
- go.mod
- go.sum
> Add tango example
